### PR TITLE
255 improve the predict output

### LINKED ISSUE #255: Improve the predict output file options
# Issue description

Currently, `predict/deepreg_predict` saves input images/labels for different label pairs, with both png and nifti file formats. This leads to sizable written files.

1 - Add options that can turn off the following for space-saving/speed:
- Save input images/labels (useful for debugging or research);
- Save png files
- Save nifti files (is this useful to be able to turn off?)

2 - Avoid saving the same input files multiple times.

## Type of Issue

- [ ] New feature request
- [ ] Documentation update
- [ ] Test request

### PR DESCRIPTION
**Pull request by mathpluscode**
# Description

- remove redundant outputs
- make both nifti and png saving configurable
- updated the docs

Fixes #255

## Type of change
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by mathpluscode** [comment]
@YipengHu @NMontanaBrown @s-sd do you want to make the saving of moving/fixed image configurable?

As we are now using indexes to identify/save image pairs, without moving/fixed image, it's impossible to refind them. That's why I didn't add this option.

Further, to NOT BREAK the demos, when calling the function `predict`, both nifti/png savings are activated by default. If not setting a default value, codes can break. (I do not have an automatic way to test demos)

**Comment by YipengHu** [comment]
also, it would be nice to have a summary in doc what will be saved. just a paragraph with CLI deepreg_predict?

**Comment by mathpluscode** [comment]
> also, it would be nice to have a summary in doc what will be saved. just a paragraph with CLI deepreg_predict?

@YipengHu this is exactly https://github.com/DeepRegNet/DeepReg/issues/242

**Comment by YipengHu** [comment]
the pred_fixed_image is in label folders - it is good to accommodate the conditional and future expansion, but still potentially waste of hard disk

**Comment by mathpluscode** [comment]
> the pred_fixed_image is in label folders - it is good to accommodate the conditional and future expansion, but still potentially waste of hard disk

Agree, need to change the output depending on the model type.

Also need to check the test coverage, will change this to WIP.

**Comment by YipengHu** [comment]
also i think it should just break the back compatibility to change the default not saving png and input?

**Comment by mathpluscode** [comment]
@YipengHu I don't know, need to ask all authors of demos if they are using the png output

**Comment by YipengHu** [comment]
> > also i think it should just break the back compatibility to change the default not saving png and input?
> 
> @YipengHu I don't know, need to ask all authors of demos if they are using the png output

I will have a look how big the default now is

**Pull request merged**
