### PR TITLE
100 preprocess unit testing

### LINKED ISSUE #100: Test + docs: dataset/preprocess
# Issue description

Unit tests + documentation for 2 functions in deepreg/dataset/preprocess

- AffineTransformation3D
- preprocess: dependent on AffineTransformation3D

This is heavily dependent on layer_utils - issue #55. So we need to resolve ticket #55 before we tackle this, likely

## Type of Issue

Please delete options that are not relevant.
- [x] Documentation update
- [x] Test request
- [x] Linting request

#### What's the expected result?
Unit tests for outputs, types, shapes. Linting requests, docstrings and docs updates.

### PR DESCRIPTION
**Pull request by mathpluscode**
# Description

Fixes #100

## Type of change

- [x] Adding unit tests

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by zacbaum** [comment]
@NMontanaBrown (or someone else with more experience with codecov... @YipengHu @mathpluscode ?)

Is the reason it doesn't cover the `transform()` function in the report because the tests for it are named `test_transform_no_labels()` and `test_transform_with_labels()`? If so... Let me know and I will combine those into one test (`test_transform()`) to get coverage up for this set of tests.

See [here](https://codecov.io/gh/ucl-candi/DeepReg/pull/151/changes) for report, and [here ](https://github.com/ucl-candi/DeepReg/pull/151/files#diff-7c64a6a83ef4bc7906b1212c8e5612daR71-R163) for relevant code that may need to be changed.

**Comment by zacbaum** [comment]
> @NMontanaBrown (or someone else with more experience with codecov... @YipengHu @mathpluscode ?)
> 
> Is the reason it shows that these tests don't cover the `transform()` function in the report because the tests for it are named `test_transform_no_labels()` and `test_transform_with_labels()`? If so... Let me know and I will combine those into one test (`test_transform()`) to get coverage up for this set of tests.
> 
> See [here](https://codecov.io/gh/ucl-candi/DeepReg/pull/151/changes) for report, and [here ](https://github.com/ucl-candi/DeepReg/pull/151/files#diff-7c64a6a83ef4bc7906b1212c8e5612daR71-R163) for relevant code that may need to be changed.

Seems that doing this (as in commit [here](https://github.com/ucl-candi/DeepReg/pull/151/commits/64c70820a8773e9f9d7e7e2c95534d01c760e164)) didn't change things.

**Comment by YipengHu** [comment]
> > @NMontanaBrown (or someone else with more experience with codecov... @YipengHu @mathpluscode ?)
> > Is the reason it shows that these tests don't cover the `transform()` function in the report because the tests for it are named `test_transform_no_labels()` and `test_transform_with_labels()`? If so... Let me know and I will combine those into one test (`test_transform()`) to get coverage up for this set of tests.
> > See [here](https://codecov.io/gh/ucl-candi/DeepReg/pull/151/changes) for report, and [here ](https://github.com/ucl-candi/DeepReg/pull/151/files#diff-7c64a6a83ef4bc7906b1212c8e5612daR71-R163) for relevant code that may need to be changed.
> 
> Seems that doing this (as in commit [here](https://github.com/ucl-candi/DeepReg/pull/151/commits/64c70820a8773e9f9d7e7e2c95534d01c760e164)) didn't change things.

sorry - i can definitely use a tutorial for this...

**Comment by NMontanaBrown** [comment]
Working on this ticket, updates as they come! @mathpluscode @zacbaum @YipengHu 

Firstly, running tests locally with pytest like:
`pytest ./test/unit/test_preprocess.py --cov-report  term-missing --cov `
from Deepreg dir reveals the same coverage errors as reported in the codecov report. So, might be a particularity with pytest or something with the tests - codecov just picks up the coverage reports generated by pytest and uploads them online. I will do a thorough review and potentially muck around on my fork to see what I can figure out re tests.

I will do mini presentation for codecov/pytest reports next week to fill everyone in and avoid confusion. It really is just an API that pulls from local pytest-cov reports, but fancy and with graphs - still warrants clearing up on my behalf so that we can utilise pytest-cov/codecv tools as best as possible! 😄

**Comment by NMontanaBrown** [comment]
Ok I solved this 😃:

tf.function is not executed which decreases code coverage. Before calling the method, add:
`tf.config.experimental_run_functions_eagerly(True)`
before [line 102 in test_preprocess.py](https://github.com/ucl-candi/DeepReg/blob/64c70820a8773e9f9d7e7e2c95534d01c760e164/test/unit/test_preprocess.py#L101). This should disable tf.function and carry out tests in eager execution. Coverage up to 100%! 

To test locally, do `pytest ./test/unit/test_preprocess.py --cov-report term-missing --cov`, get:

deepreg_cov
@zacbaum @mathpluscode @YipengHu

**Comment by NMontanaBrown** [comment]
Probably need to pull from master again... Then will approve, all looks sensible to me @zacbaum

**Comment by zacbaum** [comment]
> Probably need to pull from master again... Then will approve, all looks sensible to me @zacbaum

Done and done! Feel free to approve once CI done :)

**Comment by mathpluscode** [comment]
Oh nice!!!!! Can you updated the contributing tool on this point? @NMontanaBrown

**Pull request merged**
