### PR TITLE
Issue #436: do not normalize DDF/DVF before saving them

### LINKED ISSUE #436: DDF get normalized before being saved in predict
## Subject of the issue

When saving DDF/DVF in png/nifti formats, values got normalized first. 
[Code](https://github.com/DeepRegNet/DeepReg/blob/main/deepreg/predict.py#L170)
However, we would need the saved nifti output for `deepreg_warp`. 

The correct way is, not changing the values at all when being saved in nifti formats, and normalize the values for png if required in the argument.

## Your environment

- DeepReg version (commit hash or tag)

  d53a8d663acd765a67a47af3b8a3bdcfb958a4fd

## Expected behaviour

Saved values in nifti for DDF/DVF should be exactly the output of model

## Actual behaviour

DDF/DVF got normalized before being saved.

### PR DESCRIPTION
**Pull request by mathpluscode**
# Description

Fixes #436

## Type of change

What types of changes does your code introduce to DeepReg? _Put an `x` in the boxes that
apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation Update (fix or improvement on the documentation)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR.
If you're unsure about any of them, don't hesitate to ask. We're here to help! This is
simply a reminder of what we are going to look for before merging your code._

- [x] I have
      [installed pre-commit](https://deepreg.readthedocs.io/en/latest/contributing/setup.html)
      and formatted all changed files.
- [x] My commits' message styles matches
      [our requested structure](https://deepreg.readthedocs.io/en/latest/contributing/commit.html),
      e.g. `Issue #<issue number>: detailed message`.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by YipengHu** [comment]
Still a bit unclear to me - i think it worth to write a short doc for it. @mathpluscode ?

**Comment by mathpluscode** [comment]
> Still a bit unclear to me - i think it worth to write a short doc for it. @mathpluscode ?

As values have to be normalized between 0-255 (or 0-1) for png files (Nifti files are not impacted),
all images (`moving_image`, `fixed_image` and `pred_fixed_image`) 
and displacement/velocity fields (`ddf` and `dvf`) will be normalized before being saved.
Labels (`moving_label`, `fixed_label` and `pred_fixed_label`) are not affected 
as they are already within 0~1.

**Comment by mathpluscode** [comment]
Btw, maybe it's a good time to cover all the code in modified files.

**Comment by mathpluscode** [comment]
> Btw, maybe it's a good time to cover all the code in modified files.

Checked the uncovered code in train/predict/warp, it's not obvious to fix them so let it go for now.

**Review by YipengHu — APPROVED** [review]

**Pull request merged**
