### PR TITLE
708 log more metrics in tensorboard

### LINKED ISSUE #708: Log more metrics in tensorboard
## Subject of the feature

What are you trying to do and how would you want to do it differently?

Trying to debug using tensorboard, to see if any metric blows up.

Is it something you currently you cannot do?

Yes

Is this related to an issue/problem?

No

Has the feature been requested before? If yes, please provide a link to the issue.

No

image

current tensorboard contains limited metrics, we need to track more. In particular, the loss during the epoch should be tracked.

TODO
- [ ] Allow to adjust `update_freq`
- [ ] log TRE if data are labeled
- [ ] log vis of ddf, warped moving image, fixed image, etc.

### PR DESCRIPTION
**Pull request by mathpluscode**
# Description

Fixes #708

Added
- support for `update_freq`
- TRE metric when data are labeled
- stats (min/max/mean) on fixed/moving images/labels and DDF

## Type of change

What types of changes does your code introduce to DeepReg?

_Please check the boxes that apply after submitting the pull request._

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation Update (fix or improvement on the documentation)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Other (if none of the other choices apply)

## Checklist

_Please check the boxes that apply after submitting the pull request._

_If you're unsure about any of them, don't hesitate to ask. We're here to help! This is
simply a reminder of what we are going to look for before merging your code._

- [x] I have
      [installed pre-commit](https://deepreg.readthedocs.io/en/latest/contributing/setup.html)
      using `pre-commit install` and formatted all changed files. If you are not
      certain, run `pre-commit run --all-files`.
- [ ] My commits' message styles matches
      [our requested structure](https://deepreg.readthedocs.io/en/latest/contributing/commit.html),
      e.g. `Issue #<issue number>: detailed message`.
- [x] I have updated the
      [change log file](https://github.com/DeepRegNet/DeepReg/blob/main/CHANGELOG.md)
      regarding my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by mathpluscode** [comment]
@YipengHu Adding images in tensorboard is a bit more complicated, thus I will leave that for another issue.

Otherwise, are these any other scalar metrics we may track?

**Comment by mathpluscode** [comment]
@YipengHu @NMontanaBrown would you have time for this :)

**Comment by YipengHu** [comment]
> @YipengHu @NMontanaBrown would you have time for this :)

will get to this today. Nina is away.

**Comment by YipengHu** [comment]
I think we need to add Dice(binary=True) as a metric for all labelled data, regardless if it is used for loss - you can still report Dice(Binary=False) as a metric if it is used as a loss. Does it makes sense? @mathpluscode

**Review by YipengHu — APPROVED** [review]

**Review by kate-sann5100 — APPROVED** [review]

**Pull request merged**
