### PR TITLE
Issue #458: remove checkout from docker file

### LINKED ISSUE #458: Fix docker file
## Subject of the issue

There's a leftover in https://github.com/DeepRegNet/DeepReg/blob/main/Dockerfile#L21,
where I checkout the branch explicitly.

We just need to remove that `git checkout`

### PR DESCRIPTION
**Pull request by mathpluscode**
# Description

Fixes #458

## Type of change

What types of changes does your code introduce to DeepReg? _Put an `x` in the boxes that
apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation Update (fix or improvement on the documentation)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR.
If you're unsure about any of them, don't hesitate to ask. We're here to help! This is
simply a reminder of what we are going to look for before merging your code._

- [x] I have
      [installed pre-commit](https://deepreg.readthedocs.io/en/latest/contributing/setup.html)
      and formatted all changed files.
- [x] My commits' message styles matches
      [our requested structure](https://deepreg.readthedocs.io/en/latest/contributing/commit.html),
      e.g. `Issue #<issue number>: detailed message`.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by mathpluscode** [comment]
Hi @sbb-gh, I've corrected the docker file in this branch, could you check if this works for you?
I've tested locally and it's working fine :D

Otherwise, @YipengHu @zacbaum @s-sd If you could kindly check this PR.

**Review by YipengHu — APPROVED** [review]
works for me.

**Comment by s-sd** [comment]
@mathpluscode, I do not have docker currently installed on my mchine and I am also not in the docker group on the WEISS computers. So I think It might be easier/ quicker if somone that already has docker set up on their local machine or is in the docker group on the WEISS computers could test the change and review.

**Comment by mathpluscode** [comment]
> @mathpluscode, I do not have docker currently installed on my mchine and I am also not in the docker group on the WEISS computers. So I think It might be easier/ quicker if somone that already has docker set up on their local machine or is in the docker group on the WEISS computers could test the change and review.

If I remember it correctly, PT3 has docker installed ^^ I've requested the installation on all other PT machines.
Also if you want feel free to try installing docker on your machine, https://deepreg.readthedocs.io/en/latest/getting_started/install.html#use-docker here is the instructions and feel free to point out any error/missing info.

**Review by s-sd — APPROVED** [review]
@mathpluscode, thanks for the help! I was able to install docker on my machine. Sorry all the downloads took a bit long but everything works well

**Pull request merged**
