### PR TITLE
Issue #452: use eps instead of div_no_nan for division

### LINKED ISSUE #452: error while using "gmi" for the loss
## Subject of the issue

getting `tensorflow.python.framework.errors_impl.InvalidArgumentError: Nan in summary histogram for: local_net/down_sample_resnet_block/conv3d_block/conv3d/conv3d_1/kernel_0 [Op:WriteHistogramSummary]` while trying to use 'gmi' in several scenarios (e.g. in the demos)

If the bug is confirmed, would you be willing to submit a PR? _(Help can be provided if
you need assistance submitting a PR)_

No

## Your environment

- DeepReg version (commit hash or tag): 0.1.0b1 (from `git rev-parse HEAD`: 8b8d75fdaaf89be2dfefc1d5c3c37e3ef26fd7d1)

- OS: Linux 4.15.0-112-generic #113-Ubuntu  x86_64 x86_64 x86_64 GNU/Linux

- Python Version: 3.7.9

- TensorFlow: 2.2.0

## Steps to reproduce

modified the grouped_mr_heart demo yaml file with 'gmi' instead of 'lncc' and then run
`deepreg_train --gpu "3" --config_path demos/grouped_mr_heart/grouped_mr_heart.yaml --log_dir grouped_mr_heart`

log 

```
1/9 [==>...........................] - ETA: 0s - loss/weighted_regularization: 0.0000e+00 - loss: nan - loss/weighted_image_dissimilarity: nan - loss/regularization: 0.0000e+00 - loss/image_dissimilarity: nan2020-10-15 08:42:22.326944: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1430] function cupti_interface_->EnableCallback( 0 , subscriber_, CUPTI_CB_DOMAIN_DRIVER_API, cbid)failed with error CUPTI_ERROR_INVALID_PARAMETER
2020-10-15 08:42:22.330619: I tensorflow/core/profiler/internal/gpu/device_tracer.cc:216]  GpuTracer has collected 0 callback api events and 0 activity events.
2020-10-15 08:42:22.349700: I tensorflow/core/profiler/rpc/client/save_profile.cc:168] Creating directory: logs/grouped_mr_heart/train/plugins/profile/2020_10_15_08_42_22
2020-10-15 08:42:22.352329: I tensorflow/core/profiler/rpc/client/save_profile.cc:174] Dumped gzipped tool data for trace.json.gz to logs/grouped_mr_heart/train/plugins/profile/2020_10_15_08_42_22/MMIV-DGX-Station2.trace.json.gz
2020-10-15 08:42:22.353773: I tensorflow/core/profiler/utils/event_span.cc:288] Generation of step-events took 0.001 ms

2020-10-15 08:42:22.355437: I tensorflow/python/profiler/internal/profiler_wrapper.cc:87] Creating directory: logs/grouped_mr_heart/train/plugins/profile/2020_10_15_08_42_22Dumped tool data for overview_page.pb to logs/grouped_mr_heart/train/plugins/profile/2020_10_15_08_42_22/MMIV-DGX-Station2.overview_page.pb
Dumped tool data for input_pipeline.pb to logs/grouped_mr_heart/train/plugins/profile/2020_10_15_08_42_22/MMIV-DGX-Station2.input_pipeline.pb
Dumped tool data for tensorflow_stats.pb to logs/grouped_mr_heart/train/plugins/profile/2020_10_15_08_42_22/MMIV-DGX-Station2.tensorflow_stats.pb
Dumped tool data for kernel_stats.pb to logs/grouped_mr_heart/train/plugins/profile/2020_10_15_08_42_22/MMIV-DGX-Station2.kernel_stats.pb

2/9 [=====>........................] - ETA: 2s - loss/weighted_regularization: nan - loss: nan - loss/weighted_image_dissimilar3/9 [=========>....................] - ETA: 3s - loss/weighted_regularization: nan - loss: nan - loss/weighted_image_dissimilar4/9 [============>.................] - ETA: 3s - loss/weighted_regularization: nan - loss: nan - loss/weighted_image_dissimilar5/9 [===============>..............] - ETA: 2s - loss/weighted_regularization: nan - loss: nan - loss/weighted_image_dissimilar6/9 [===================>..........] - ETA: 2s - loss/weighted_regularization: nan - loss: nan - loss/weighted_image_dissimilar7/9 [======================>.......] - ETA: 1s - loss/weighted_regularization: nan - loss: nan - loss/weighted_image_dissimilar8/9 [=========================>....] - ETA: 0s - loss/weighted_regularization: nan - loss: nan - loss/weighted_image_dissimilar9/9 [==============================] - ETA: 0s - loss/weighted_regularization: nan - loss: nan - loss/weighted_image_dissimilarity: nan - loss/regularization: nan - loss/image_dissimilarity: nan2020-10-15 08:42:34.992438: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at summary_kernels.cc:242 : Invalid argument: Nan in summary histogram for: local_net/down_sample_resnet_block/conv3d_block/conv3d/conv3d_1/kernel_0
Traceback (most recent call last):
  File "/home/charlie/anaconda3/envs/deepreg/lib/python3.7/site-packages/tensorflow/python/ops/gen_summary_ops.py", line 464, in write_histogram_summary
    tld.op_callbacks, writer, step, tag, values)
tensorflow.python.eager.core._FallbackException: This function does not handle the case of the path where all inputs are not already EagerTensors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/charlie/anaconda3/envs/deepreg/bin/deepreg_train", line 33, in <module>
    sys.exit(load_entry_point('deepreg', 'console_scripts', 'deepreg_train')())
  File "/home/charlie/3DREG-tests/DeepReg/deepreg/train.py", line 227, in main
    log_dir=args.log_dir,
  File "/home/charlie/3DREG-tests/DeepReg/deepreg/train.py", line 154, in train
    callbacks=callbacks,
  File "/home/charlie/anaconda3/envs/deepreg/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 66, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/charlie/anaconda3/envs/deepreg/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 876, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/charlie/anaconda3/envs/deepreg/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py", line 365, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/charlie/anaconda3/envs/deepreg/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py", line 2000, in on_epoch_end
    self._log_weights(epoch)
  File "/home/charlie/anaconda3/envs/deepreg/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py", line 2119, in _log_weights
    summary_ops_v2.histogram(weight_name, weight, step=epoch)
  File "/home/charlie/anaconda3/envs/deepreg/lib/python3.7/site-packages/tensorflow/python/ops/summary_ops_v2.py", line 830, in histogram
    return summary_writer_function(name, tensor, function, family=family)
  File "/home/charlie/anaconda3/envs/deepreg/lib/python3.7/site-packages/tensorflow/python/ops/summary_ops_v2.py", line 759, in summary_writer_function
    should_record_summaries(), record, _nothing, name="")
  File "/home/charlie/anaconda3/envs/deepreg/lib/python3.7/site-packages/tensorflow/python/framework/smart_cond.py", line 54, in smart_cond
    return true_fn()
  File "/home/charlie/anaconda3/envs/deepreg/lib/python3.7/site-packages/tensorflow/python/ops/summary_ops_v2.py", line 752, in record
    with ops.control_dependencies([function(tag, scope)]):
  File "/home/charlie/anaconda3/envs/deepreg/lib/python3.7/site-packages/tensorflow/python/ops/summary_ops_v2.py", line 828, in function
    name=scope)
  File "/home/charlie/anaconda3/envs/deepreg/lib/python3.7/site-packages/tensorflow/python/ops/gen_summary_ops.py", line 469, in write_histogram_summary
    writer, step, tag, values, name=name, ctx=_ctx)
  File "/home/charlie/anaconda3/envs/deepreg/lib/python3.7/site-packages/tensorflow/python/ops/gen_summary_ops.py", line 490, in write_histogram_summary_eager_fallback
    attrs=_attrs, ctx=ctx, name=name)
  File "/home/charlie/anaconda3/envs/deepreg/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Nan in summary histogram for: local_net/down_sample_resnet_block/conv3d_block/conv3d/conv3d_1/kernel_0 [Op:WriteHistogramSummary]
```

### PR DESCRIPTION
**Pull request by mathpluscode**
# Description

The reason for the bug was related to `tf.math.div_no_nan` which returns 0 when we do division by 0, but the gradient for this might not be well defined and it causes some layers to have non-numeric weights (nan/inf).

Therefore the solution is to add a machine epsilon to both numerator and denominator for the division. Here, instead of defining it manually, we use `tf.keras.backend.epsilon()` which is actually `1e-7` because the machine epsilon for float32 is smaller than 1e-7 but bigger than 1e-8.

```
>>> import numpy as np
>>> np.finfo(np.float32).eps
1.1920929e-07
>>> np.finfo(np.float16).eps
0.000977
```

Fixes #452 

## Type of change

What types of changes does your code introduce to DeepReg? _Put an `x` in the boxes that
apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation Update (fix or improvement on the documentation)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR.
If you're unsure about any of them, don't hesitate to ask. We're here to help! This is
simply a reminder of what we are going to look for before merging your code._

- [x] I have
      [installed pre-commit](https://deepreg.readthedocs.io/en/latest/contributing/setup.html)
      and formatted all changed files.
- [x] My commits' message styles matches
      [our requested structure](https://deepreg.readthedocs.io/en/latest/contributing/commit.html),
      e.g. `Issue #<issue number>: detailed message`.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by mathpluscode** [comment]
Hi, @acasamitjana @agrimwood, would you have time to review this PR ;) thx!

**Comment by acasamitjana** [comment]
Hey, nice catch. I have a couple of comments:

1. I'm not sure it is best to add EPS to the numerator. Is that because in the extreme case of 0/0 you'd like to see a 1? I may agree with that, but there are other cases where it may not work. 
    - (0+EPS)/(b+EPS) would produce wrong results if b ~EPS (ideally should output 0, instead ~0.5).
    - (a+EPS)/(0+EPS) would produce wrong results if a~EPS (ideally should output some big number, instead ~2). 
I believe this could (potentially) be bad for metrics between [0,1] or when applying the log(). Correct me if I'm wrong.

2. What about the log(x)? I think that it may be useful to add log(x+EPS) in MI and BCE.

3. With (1) and (2) in mind, I'd go for a/(b+EPS) and log(a + EPS). E.g: for GMI, log(a/(b+EPS) + EPS)

**Comment by mathpluscode** [comment]
> Hey, nice catch. I have a couple of comments:
> 
> 1. I'm not sure it is best to add EPS to the numerator. Is that because in the extreme case of 0/0 you'd like to see a 1? I may agree with that, but there are other cases where it may not work.
>    
>    * (0+EPS)/(b+EPS) would produce wrong results if b ~EPS (ideally should output 0, instead ~0.5).
>    * (a+EPS)/(0+EPS) would produce wrong results if a~EPS (ideally should output some big number, instead ~2).
>      I believe this could (potentially) be bad for metrics between [0,1] or when applying the log(). Correct me if I'm wrong.
> 2. What about the log(x)? I think that it may be useful to add log(x+EPS) in MI and BCE.
> 3. With (1) and (2) in mind, I'd go for a/(b+EPS) and log(a + EPS). E.g: for GMI, log(a/(b+EPS) + EPS)
> 
> Apart from that, I see that it fails a non-required test so that's not a problem to be approved. But, can you explain me what is this test about?

Hi @acasamitjana, thx! Nice point with the EPS, it was just mainly prevent 0/0. So yes, fine with your proposition!

For the tests, it’s about the code coverage.
The passing one is to make shire that all all changes in the current PR are covered with tests. The failed one is to ask the total test coverage is not decreasing, but this sometimes is influenced by some minor changes, so I’d argue smaller than 0.1 percentage is fine. That’s my understanding :)

**Comment by acasamitjana** [comment]
It's an approve for me. Let's wait for @agrimwood answer, otherwise we may want to ask for another reviewer.

**Review by acasamitjana — APPROVED** [review]

**Comment by mathpluscode** [comment]
@acasamitjana maybe we need to review the changes related to 0/0.

For example, when calculating dice score, assuming we have only background/foreground and the label is all zero, means there's no foreground. We would want the model to have zero prediction.

We know that the dice score (not loss) is calculated as follows:

```python
numerator = sum(y_true * y_pred) * 2
denominator = sum(y_true) + sum(y_pred)
```

Therefore if the prediction is perfect, we will have `numerator = denominator = 0`.
We would want the dice score to be 1, as the prediction is perfect.
But 0 / (0 + EPS) = 0, which gives 0. This can be incorrect for the training.

What do you think?

**Comment by acasamitjana** [comment]
I agree that for the problem at hand, we should add EPS to both numerator/denominator. Sorry for changing that.

**Comment by mathpluscode** [comment]
@acasamitjana @agrimwood I've synced the code with main branch ;) please have another quick look. Thx!

**Review by acasamitjana — APPROVED** [review]

**Review by agrimwood — APPROVED** [review]
Adding EPS to both denominator and numerator is a sensible precaution, even if there are rare edge cases where the result is incorrect.
The code is sound.

**Pull request merged**
