### PR TITLE
Issue #573: add two badges

### LINKED ISSUE #573: Code quality badge using scrutinizer and codeclimate
## Subject of the feature

Two new badges (https://github.com/fepegar/torchio uses these ^^)

<a href="scrutinizer-ci.com/g/DeepRegNet/DeepReg">
Code Quality
</a>

<a href="https://codeclimate.com/github/DeepRegNet/DeepReg/maintainability"></a>

It can help us to identify some duplicated code, improve code structure, etc.

### PR DESCRIPTION
**Pull request by mathpluscode**
# Description

Fixes #573

## Type of change

What types of changes does your code introduce to DeepReg?

_Please check the boxes that apply after submitting the pull request._

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Documentation Update (fix or improvement on the documentation)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (if none of the other choices apply)

## Checklist

_Please check the boxes that apply after submitting the pull request._

_If you're unsure about any of them, don't hesitate to ask. We're here to help! This is
simply a reminder of what we are going to look for before merging your code._

- [x] I have
      [installed pre-commit](https://deepreg.readthedocs.io/en/latest/contributing/setup.html)
      using `pre-commit install` and formatted all changed files. If you are not
      certain, run `pre-commit run --all-files`.
- [x] My commits' message styles matches
      [our requested structure](https://deepreg.readthedocs.io/en/latest/contributing/commit.html),
      e.g. `Issue #<issue number>: detailed message`.
- [x] I have updated the
      [change log file](https://github.com/DeepRegNet/DeepReg/blob/main/CHANGELOG.md)
      regarding my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by mathpluscode** [comment]
@NMontanaBrown @YipengHu @zacbaum ^^ I know you are fans of badges!

**Comment by mathpluscode** [comment]
image

**Review by YipengHu — APPROVED** [review]
👍 why not

**Comment by YipengHu** [comment]
Also update docs please...

**Review by zacbaum — APPROVED** [review]

**Pull request merged**
