### PR TITLE
#397: Add entry-point for extra data downloads

### LINKED ISSUE #397: Dependency on cloned repo
## Subject of the feature

Currently the Quick Start is dependent on test data, config and absolute path, while demos are dependent on absolute path. Therefore, the PyPI installed DeepReg needs to manually download test data and config to run Quick Start, and demos need change path manually.
It would be ideal to remove this dependency.

If the feature request is approved, would you be willing to submit a PR? _(Help can be
provided if you need assistance submitting a PR)_

Yes

### PR DESCRIPTION
**Pull request by zacbaum**
Similarly to deepreg_train/predict/warp/etc. this provides a simple command line tool for users to download the data, config and demos folders to their computer without needing to checkout the git repo (aka, those who just `pip install deepreg`).

# Description

Usage:

`deepreg_download  --output_dir XXX`
or
`deepreg_download -d XXX`

Not using the directory output will download into the current working directory.

Testing this:

1. Clone from github, delete the ./config, ./demos and ./data folder.
2. Create your anaconda env as in install (`conda env create -f environment.yml;
conda activate deepreg` or `conda env create -f environment_cpu.yml;
conda activate deepreg` if CPU only)
3. `pip install -e .` from within the repo's main directory
4. Enter either of the usage options as above
5. Should download all files from the three folders needed (config, data, demos)

You can view updated docs here: https://deepreg--553.org.readthedocs.build/en/553/getting_started/install.html

Before adding tests I wanted to make sure this works for others - so if someone can please test and let me know.

Fixes #397 

## Type of change

What types of changes does your code introduce to DeepReg?

_Please check the boxes that apply after submitting the pull request._

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Documentation Update (fix or improvement on the documentation)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Other (if none of the other choices apply)

## Checklist

_Please check the boxes that apply after submitting the pull request._

_If you're unsure about any of them, don't hesitate to ask. We're here to help! This is
simply a reminder of what we are going to look for before merging your code._

- [x] I have [installed pre-commit](https://deepreg.readthedocs.io/en/latest/contributing/setup.html) using `pre-commit install` and formatted all changed files. If you are not certain, run `pre-commit run --all-files`.
- [x] My commits' message styles matches [our requested structure] https://deepreg.readthedocs.io/en/latest/contributing/commit.html), e.g. `Issue #<issue number>: detailed message`.
- [x] I have updated the [change log file](https://github.com/DeepRegNet/DeepReg/blob/main/CHANGELOG.md) regarding my changes.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by zacbaum** [comment]
@YipengHu @NMontanaBrown - If you are able to try this out on your machines, please let me know if it works.

I think once we know it does work, I will need to add some exception handling for wrong passwords, etc (e.g. if HTTP request returns bad auth codes). But for now, if you enter the right password this should work! 😄 

Will add tests, info in quick-start docs, and update change-log once we know it works for someone other than me,..

**Comment by YipengHu** [comment]
Will try. Needing password is annoying?

**Comment by zacbaum** [comment]
> Will try. Needing password is annoying?

Can be done without, but because of the number of files that we need to download, we run out of "non-authenticated" https requests - so without username/password it may not work properly.

**Comment by YipengHu** [comment]
> > Will try. Needing password is annoying?
> 
> Can be done without (aka if you just run deepreg_download with no arguments it will work usually), but because of the number of files that we need to download, we run out of "non-authenticated" https requests - so without username/password it may not work properly.

is it better to just download config and script this way, instead of downloading actual data/model? when one needs to run any demo, still suing the download script to download as before?

**Comment by YipengHu** [comment]
> > > Will try. Needing password is annoying?
> > 
> > 
> > Can be done without (aka if you just run deepreg_download with no arguments it will work usually), but because of the number of files that we need to download, we run out of "non-authenticated" https requests - so without username/password it may not work properly.
> 
> is it better to just download config and script this way, instead of downloading actual data/model? when one needs to run any demo, still suing the download script to download as before?

wait, i see you are actually doing this - it will run out of requests? is it based on number of requests or data size?

**Comment by zacbaum** [comment]
> > is it better to just download config and script this way, instead of downloading actual data/model? when one needs to run any demo, still suing the download script to download as before?
> 
> wait, i see you are actually doing this - it will still run out of requests? is it based on number of requests or data size?

It's based on number of requests, see [here](https://docs.github.com/en/free-pro-team@latest/rest/overview/resources-in-the-rest-api#rate-limiting):

> *For unauthenticated requests, the rate limit allows for up to 60 requests per hour. Unauthenticated requests are associated with the originating IP address, and not the user making requests.*

**Comment by NMontanaBrown** [comment]
Checking now.

**Comment by zacbaum** [comment]
Another option:

Download the entire repo via this link to some temp folder, https://github.com/DeepRegNet/DeepReg/archive/main.zip, and then move/extract to the right place and delete the files/folders we don't need.

**Comment by NMontanaBrown** [comment]
Hi, this is not working for me, bash throws an error with non string items in my password. @zacbaum

**Comment by zacbaum** [comment]
> Hi, this is not working for me, bash throws an error with non letter items in my password. @zacbaum
> 
> I also tried to put my password between "" but it didn't work.
> 
> EDIT:
> Error: -bash: **: event not found,
> 
> I starred out the event for security.

Thanks @NMontanaBrown - Could you let me know the full command (without password) that you entered and if there's more to the error as well please post that!

I'll see if I can reproduce on bash. I think we will also likely end up doing this:

> Another option:
>
>Download the entire repo via this link to some temp folder, https://github.com/DeepRegNet/DeepReg/archive/main.zip, and then move/extract to the right place and delete the files/folders we don't need.

After chatting with @YipengHu earlier today.

**Comment by NMontanaBrown** [comment]
> > Hi, this is not working for me, bash throws an error with non letter items in my password. @zacbaum
> > I also tried to put my password between "" but it didn't work.
> > EDIT:
> > Error: -bash: **: event not found,
> > I starred out the event for security.
> 
> Thanks @NMontanaBrown - Could you let me know the full command (without password) that you entered and if there's more to the error as well please post that!
> 
> I'll see if I can reproduce on bash. I think we will also likely end up doing this:
> 
> > Another option:
> > Download the entire repo via this link to some temp folder, https://github.com/DeepRegNet/DeepReg/archive/main.zip, and then move/extract to the right place and delete the files/folders we don't need.
> 
> After chatting with @YipengHu earlier today.

deepreg_download --username NMontanaBrown --password "**" --output_dir ./

and 

deepreg_download --username NMontanaBrown --password ** --output_dir ./

From within the DeepReg folder, on macOS, from bash terminal.

**Comment by NMontanaBrown** [comment]
@zacbaum Working on Ubuntu Bionic Beaver terminal, which is also bash based...? Weird. Doesn;t throw the same error. But not sure if it's logging me in or not. Same commands as above.

**Comment by zacbaum** [comment]
> @zacbaum Working on Ubuntu Bionic Beaver terminal, which is also bash based...? Weird. Doesn;t throw the same error. But not sure if it's logging me in or not. Same commands as above.

Fo reference: adding single quotes around the string corrects this, the issue involved the string starting with a !, and triggering history expansion in the shell. For more info, see [here](https://www.gnu.org/software/bash/manual/html_node/History-Interaction.html)

**Comment by NMontanaBrown** [comment]
> > @zacbaum Working on Ubuntu Bionic Beaver terminal, which is also bash based...? Weird. Doesn;t throw the same error. But not sure if it's logging me in or not. Same commands as above.
> 
> Fo reference: adding single quotes around the string corrects this, the issue involved the string starting with a !, and triggering history expansion in the shell. For more info, see [here](https://www.gnu.org/software/bash/manual/html_node/History-Interaction.html)
> 
> Edit: @YipengHu - another reason we should probably not require credentials to download....! The odds are ever stacking against me...

Possible to implement some ssh protocol? I feel icky about putting my password in a bash terminal to be read on my screen. Potential safety concerns.

**Comment by YipengHu** [comment]
> > > @zacbaum Working on Ubuntu Bionic Beaver terminal, which is also bash based...? Weird. Doesn;t throw the same error. But not sure if it's logging me in or not. Same commands as above.
> > 
> > Fo reference: adding single quotes around the string corrects this, the issue involved the string starting with a !, and triggering history expansion in the shell. For more info, see [here](https://www.gnu.org/software/bash/manual/html_node/History-Interaction.html)
> > 
> > Edit: @YipengHu - another reason we should probably not require credentials to download....! The odds are ever stacking against me...
> 
> Possible to implement some ssh protocol? I feel icky about putting my password in a bash terminal to be read on my screen. Potential safety concerns.

How?

**Comment by zacbaum** [comment]
@YipengHu @NMontanaBrown let's leave this for now, I'll implement the 

`download -> unzip to temp -> copy to WD -> delete from temp`

Which won't require authentication, so should alleviate all these concerns :)

**Comment by zacbaum** [comment]
@NMontanaBrown @YipengHu - give this a try when you can. Now downloads the zip to memory, and extracts only the files/folders that we want (config, data, demos).

If working, will update quick start guide / changelog to reflect this.

Do we want to add some unit tests for this?

**Comment by NMontanaBrown** [comment]
Working as stated. Is it possible to add tests?

**Comment by zacbaum** [comment]
> Working as stated. Is it possible to add tests?

I mean, in theory - yes. Could have something which verifies that it downloads the correct folders/files (could download them the confirm all the files exist on system) relative to a cloned git repo (though not sure how to git via python without more dependencies...)

**Comment by zacbaum** [comment]
@YipengHu  @mathpluscode if either of you can review this; thanks!

We just need to decide if we want to add tests as without it decreases coverage quite a bit.

**Comment by YipengHu** [comment]
> @YipengHu @mathpluscode if either of you can review this; thanks!
> 
> We just need to decide if we want to add tests as without it decreases coverage quite a bit.

Tests are needed. I will have a look at the other parts.

**Comment by mathpluscode** [comment]
@zacbaum thx for the efforts! lgtm in general, if we can add a test just to verify the cli tool it'd nice.

**Comment by zacbaum** [comment]
@YipengHu, @mathpluscode, have added tests for the downloader.

They are quite simple; it checks the content of the current checked-out branch (from the test script) with that which is downloaded into a temp folder from main (and deleted once the test passes).

As of now, it only compares files that are found in both cases (checked out from branch, and downloaded from main). Do we want to make this a bit more stringent?

If so... We can allow 'new' files in branch, but not from main - in case someone is adding config/data/demos in their commit. However, we shouldn't allow the other way (this ensures that we are only letting commits that are even with main be merged).

Right now, adding new files to data/config/demos should not cause tests to fail.

**Comment by mathpluscode** [comment]
image

@zacbaum would you mind adding `# pragma: no cover` to these calls of `main()` in train/predict/vis/warp/download to reduce the missing lines of coverage? as we called those funcs manually it's ok to skip these lines :) I can add them for you if you want.

**Comment by zacbaum** [comment]
> image
> 
> @zacbaum would you mind adding `# pragma: no cover` to these calls of `main()` in train/predict/vis/warp/download to reduce the missing lines of coverage? as we called those funcs manually it's ok to skip these lines :) Otherwise your branch wont pass the checks
> 
> I can add them for you if you want.

Will do!

**Review by mathpluscode — APPROVED** [review]

**Review by YipengHu — APPROVED** [review]
It is good enough for now. If we get complaints for anyone's workflow, we will adapt then, mostly likely coming from the core anyway.

**Pull request merged**
