### PR TITLE
322 s sd docs review 2

### PR DESCRIPTION
**Pull request by s-sd**
# Description

This is a continuation of #323. All the tutorials have now been reviewed. 

Partially addresses #322 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not
      work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by s-sd** [comment]
@YipengHu, this PR is a continuation of PR #323. Some tutorial docs were left to review and I have reviewed/ made minor modifications to them in this PR. It would be great if you could review. 

One small thing is that in line 119 of `docs/source/tutorial/registration.md`:
```
[data sampling API](tutorial_sampling.md) 
```
This link points to a tutorial that does not exist. Should I change or remove this?

**Comment by YipengHu** [comment]
> @YipengHu, this PR is a continuation of PR #323. Some tutorial docs were left to review and I have reviewed/ made minor modifications to them in this PR. So I have now reviewed all tutorial docs. It would be great if you could review.
> 
> One small thing is that in line 119 of `docs/source/tutorial/registration.md`:
> 
> ```
> [data sampling API](tutorial_sampling.md) 
> ```
> 
> This link points to a tutorial that does not exist. Should I change or remove this?

Remove it please.

**Comment by s-sd** [comment]
@YipengHu, removed the link

**Comment by YipengHu** [comment]
> @YipengHu, removed the link

Looks good - approved. Please merge when all the checks are done if without conflicts.

**Pull request merged**
