### PR TITLE
587 use pylint to check docstring

### LINKED ISSUE #587: Use pydocstyle and pylint to check docstring
## Subject of the feature

http://www.pydocstyle.org/en/stable/usage.html#command-line-interface

It is common to forget updating docstrings, so an automated tool can be helpful.

The docstring should also pass pylint docstring check.

## Pylint Steps

I've updated the pylint config in the branch,
1. Identify an error code, e.g. `W9012`
2. Fix all related errors, then check with `pylint --disable=all --enable=W9012 *`

### PR DESCRIPTION
**Pull request by mathpluscode**
# Description

Format all codes regarding the docstring following a certain rules defined by pylint. Checks were added in CI.

Close #587 

## Type of change

What types of changes does your code introduce to DeepReg?

_Please check the boxes that apply after submitting the pull request._

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Documentation Update (fix or improvement on the documentation)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (if none of the other choices apply)

## Checklist

_Please check the boxes that apply after submitting the pull request._

_If you're unsure about any of them, don't hesitate to ask. We're here to help! This is
simply a reminder of what we are going to look for before merging your code._

- [x] I have
      [installed pre-commit](https://deepreg.readthedocs.io/en/latest/contributing/setup.html)
      using `pre-commit install` and formatted all changed files. If you are not
      certain, run `pre-commit run --all-files`.
- [x] My commits' message styles matches
      [our requested structure](https://deepreg.readthedocs.io/en/latest/contributing/commit.html),
      e.g. `Issue #<issue number>: detailed message`.
- [x] I have updated the
      [change log file](https://github.com/DeepRegNet/DeepReg/blob/main/CHANGELOG.md)
      regarding my changes.
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by mathpluscode** [comment]
FYI @s-sd @NMontanaBrown @zacbaum @YipengHu 

I'm bringing more checks regarding code/docstring. Due to the tech debt, it will not be possible to finish them all at once.
Therefore I've prepared this example PR, which should be considered once #568 is merged.

Later if anyone is willing to help, we can distribute the error codes and every one fix some of them independently.

**Comment by YipengHu** [comment]
> FYI @s-sd @NMontanaBrown @zacbaum @YipengHu
> 
> I'm bringing more checks regarding code/docstring. Due to the tech debt, it will not be possible to finish them all at once.
> Therefore I've prepared this example PR, which should be considered once #568 is merged.
> 
> Later if anyone is willing to help, we can distribute the error codes and every one fix some of them independently.

Good to bring this to the Teams channel see who is available to help out

**Comment by mathpluscode** [comment]
@YipengHu @NMontanaBrown now time to review this one XD

**Comment by YipengHu** [comment]
> @YipengHu @NMontanaBrown now time to review this one XD

well done on this one! I will have a good look tmr...

**Review by YipengHu — APPROVED** [review]

**Comment by mathpluscode** [comment]
@s-sd if you have time by any chance ;)

**Review by s-sd — APPROVED** [review]
Looks great @mathpluscode! It might be a good idea before the merge to add a line or two in the PR description as well as the issue number.

**Comment by mathpluscode** [comment]
> Looks great @mathpluscode! It might be a good idea before the merge to add a line or two in the PR description as well as the issue number.

thx! done

**Pull request merged**
