### PR TITLE
Issue #321: unpaired mri brain demo review

### PR DESCRIPTION
**Pull request by NMontanaBrown**
# Description

Review:

- [x] Author
- [x] Disclaimer
- [x] Application - description included
- [x] Data - open accessible, linked.
- [x] Instructions
    - [x] Download - working
    - [x] Train 
    - [x] Predict - working, modified visualisation. How long has the pre-trained model been trained for? The warped image and label don't seem to change much.
- [x] Pre-trained Model - available
- [x] Tested version - included. Update to latest commit tested?
- [x] Contact - included.
- [x] References - included.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by NMontanaBrown** [comment]
Predict works well. What would team think about expanding predict script to provide more info in the visualisation? Currently we get:
visualisation

Suggestion is to expand to resemble the one in paired lung ct like:
visualisation

@YipengHu @mathpluscode @acasamitjana

**Comment by YipengHu** [comment]
Yes! We will do a gif as you @NMontanaBrown previously suggested post r1.

**Comment by NMontanaBrown** [comment]
Ok, cool, modified and now have this:

visualisation

One thing to note is that for this pre-trained model, there doesn't seem to be much change between the warped moving label and the moving label - how long was the model trained @acasamitjana?

**Comment by mathpluscode** [comment]
@NMontanaBrown  is this branch ready for merge? We'd better merge them now before switch default branch to main as PRs will have to be retargeted https://github.com/github/renaming

**Comment by NMontanaBrown** [comment]
@mathpluscode Should be ready for review now! I will raise a separate ticket about the model for this demo

**Review by mathpluscode — APPROVED** [review]

**Comment by YipengHu** [comment]
> @mathpluscode Should be ready for review now! I will raise a separate ticket about the model for this demo

@acasamitjana has been away, but should be able to have a look at this soon - and the reg. performance should not be in the way of r1.

**Pull request merged**
