### PR TITLE
251 bug when using multiple test folders

### LINKED ISSUE #251: Bug when using multiple test folders
# Issue description

Incorrect error when using multiple folder data in testing with paired dataset loader.

## Type of Issue

Please delete options that are not relevant.

- [ ] Bug report
- [ ] Test request

#### For bug report or feature request, steps to reproduce the issue, including (but not limited to):

1. OS
2. Environment to reproduce
3. What commands run / sample script used:

on branch 12, run the demo, when using the predict (see readme)

Traceback (most recent call last):
  File "/home/yipenghu/miniconda3/envs/deepreg/bin/predict", line 33, in <module>
    sys.exit(load_entry_point('deepreg', 'console_scripts', 'predict')())
  File "/home/yipenghu/git/DeepReg/deepreg/predict.py", line 352, in main
    args.config_path,
  File "/home/yipenghu/git/DeepReg/deepreg/predict.py", line 264, in predict
    save_dir=log_dir + "/test",
  File "/home/yipenghu/git/DeepReg/deepreg/predict.py", line 136, in predict_on_dataset
    "Sample is repeated, maybe the dataset has been repeated."
ValueError: Sample is repeated, maybe the dataset has been repeated.

### PR DESCRIPTION
**Pull request by mathpluscode**
# Description

Fixes #251

- remove `ConcatenatedDataLoader` as multiple dirs should not be just simply concatenated together, for unpaired data, the mixing from different dirs should be included
- rewrite h5/nifti data loaders to support multiple dirs

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not
      work as expected)
- [x] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by mathpluscode** [comment]
Maybe I should add one more test in init to check the behavior with two identical dir_path

**Comment by YipengHu** [comment]
"two identical dir_path"? parsing the same directory twice?

**Comment by YipengHu** [comment]
> Maybe I should add one more test in init to check the behavior with two identical dir_path

Just for the record here. It should be an error and if replication of data is intended, such as a workaround for resampling, one can still do it with different file/dir names.

**Comment by YipengHu** [comment]
@mathpluscode suggest to merge this now with two approvals then #12 which "depends" on this.

**Comment by mathpluscode** [comment]
@YipengHu merged

**Pull request merged**
