### PR TITLE
533 wrong bias init in globalnet

### LINKED ISSUE #533: Wrong bias initialization in GlobalNet
## Subject of the issue

In `GlobalNet`, the bias of the dense layer to output `theta` is wrong. 

```python
>>> x=tf.constant([1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0])
>>> tf.reshape(x,(4,3))
<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 1., 0.]], dtype=float32)>
```

It should be the flatten `eye(4,3)` as follows:

```python
>>> tf.reshape(tf.eye(4,3),shape=(-1))
<tf.Tensor: shape=(12,), dtype=float32, numpy=array([1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.], dtype=float32)>
```

The reason of such initialization is too ensure the initial transformation is close to identical transformation.

To be sure, we can add one more test for `warp_grid` with identical theta https://github.com/DeepRegNet/DeepReg/blob/main/deepreg/model/layer_util.py#L433.

@YipengHu @RemiDelaunay Please confirm if you agree ;)

Great thanks to @jvhoutte for the bug report.

### PR DESCRIPTION
**Pull request by mathpluscode**
# Description

Fixes #533

Would be better to take the chance to refact global net related tests.

## Type of change

What types of changes does your code introduce to DeepReg? _Put an `x` in the boxes that
apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation Update (fix or improvement on the documentation)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR.
If you're unsure about any of them, don't hesitate to ask. We're here to help! This is
simply a reminder of what we are going to look for before merging your code._

- [x] I have
      [installed pre-commit](https://deepreg.readthedocs.io/en/latest/contributing/setup.html)
      using `pre-commit install` and formatted all changed files. If you are not
      certain, run `pre-commit run --all-files`.
- [x] My commits' message styles matches
      [our requested structure](https://deepreg.readthedocs.io/en/latest/contributing/commit.html),
      e.g. `Issue #<issue number>: detailed message`.
- [ ] I have updated the
      [change log file](https://github.com/DeepRegNet/DeepReg/blob/main/CHANGELOG.md)
      regarding my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by mathpluscode** [comment]
@RemiDelaunay Please have a look if this fix is correct. We can merge the fix first as it's a bug. Then add a new ticket to refactor the tests related to `GlobalNet`. Or feel free to do it now. ;)

**Comment by mathpluscode** [comment]
@RemiDelaunay Thx! Seems like you prefer refactoring them now. So here is the updated guidelines https://deepreg.readthedocs.io/en/latest/contributing/test.html.

While it is not necessary to use `parameterize` everywhere, it is important to make tests independent from each other while possible. And `parameterize` can help you shorten the code in some cases.

Here are some examples:
- https://github.com/DeepRegNet/DeepReg/blob/main/test/unit/test_dataset_loader_util.py
- https://github.com/DeepRegNet/DeepReg/blob/main/test/unit/test_nifti_loader.py#L231

Please let me know if it's not clear ;)

**Review by RemiDelaunay — APPROVED** [review]
I just added a commit to refactor global_test_init. The changes seem to have fixed the bug.

**Comment by RemiDelaunay** [comment]
Sorry @mathpluscode  I thought you meant refactor the part you deleted in your previous commit. I don't have much time now but you can assign me and I will do it during the week.

**Comment by mathpluscode** [comment]
> Sorry @mathpluscode I thought you meant refactor the part you deleted in your previous commit. I don't have much time now but you can assign me and I will do it during the week.

Sure, will do a new issue for this ;)

**Review by YipengHu — APPROVED** [review]

**Pull request merged**
