### PR TITLE
Issue #461: add stale config for Stale robot

### PR DESCRIPTION
**Pull request by mathpluscode**
# Description

Add stale plugin.

## Type of change

What types of changes does your code introduce to DeepReg? _Put an `x` in the boxes that
apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation Update (fix or improvement on the documentation)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Other (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR.
If you're unsure about any of them, don't hesitate to ask. We're here to help! This is
simply a reminder of what we are going to look for before merging your code._

- [x] I have
      [installed pre-commit](https://deepreg.readthedocs.io/en/latest/contributing/setup.html)
      using `pre-commit install` and formatted all changed files. If you are not
      certain, run `pre-commit run --all-files`.
- [x] My commits' message styles matches
      [our requested structure](https://deepreg.readthedocs.io/en/latest/contributing/commit.html),
      e.g. `Issue #<issue number>: detailed message`.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by mathpluscode** [comment]
@zacbaum @NMontanaBrown @YipengHu @s-sd If you could have a look ;) No objection from the issue regarding robots.

**Comment by zacbaum** [comment]
Fine with this, but I would opt to leave tickets marked as stale but to *not* subsequently close them after 7 days (otherwise things will just be forgotten about). We don't want to just close low-priority tickets because someone hasn't had time to get to them.

**Comment by mathpluscode** [comment]
> Fine with this, but I would opt to leave tickets marked as stale but to _not_ subsequently close them after 7 days (otherwise things will just be forgotten about). We don't want to just close low-priority tickets because someone hasn't had time to get to them.

You can prevent the close by doing any operations. If two months later no one has done anything with the issue, and no operation is done to prevent the closure. Then I'd say it's of really low priority and we should close it and come back later or add a new issue if we want to do something again. I've subscribed to all notifications so don't worry.

**Comment by zacbaum** [comment]
> Otherwise, change to 14 days?

I like this - especially if we're meeting bi-weekly; then the stale issues can be briefly mentioned in meetings and can be confirmed "not stale" or if we should close.

**Comment by mathpluscode** [comment]
> > Otherwise, change to 14 days?
> 
> I like this - especially if we're meeting bi-weekly; then the stale issues can be briefly mentioned in meetings and can be confirmed "not stale" or if we should close.

Sure ;) we can do this!

**Comment by mathpluscode** [comment]
@zacbaum days until close have been updated ;)

**Review by zacbaum — APPROVED** [review]

**Review by YipengHu — COMMENTED** [review]
Is it better to use a different label, 'stale' maybe?

**Comment by mathpluscode** [comment]
> Is it better to use a different label, 'stale' maybe?

Ok

**Comment by mathpluscode** [comment]
> Is it better to use a different label, 'stale' maybe?

done ;) @YipengHu

**Review by YipengHu — APPROVED** [review]

**Pull request merged**
