### PR TITLE
291 pypi release

### LINKED ISSUE #291: Release: PyPi
# Issue description

Release package to PyPi.

## Type of Issue

Please delete options that are not relevant.

- [x] New feature request

### PR DESCRIPTION
**Pull request by zacbaum**
# Description

Modified setup.py and documentation (see readthedocs page for info) to prepare the pypi packages.

Fixes #291

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

Release is available on [testpypi](https://test.pypi.org/project/deepreg/), was able to download and run code. Please check all the info there is as desired. Please double check that links are working.

At least one other person should install from there (`pip install deepreg --extra-index-url=https://test.pypi.org/simple/`) and ensure working as well. The package *only* includes code required to run things; no docs/data/test.

When done, we can merge this branch, I'll package a release, upload it to pypi & the deepreg github! 😄 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by NMontanaBrown** [comment]
Testing now 😄

**Comment by NMontanaBrown** [comment]
@zacbaum errored: ☹️ 

`pip install -i https://test.pypi.org/simple/ deepreg
Looking in indexes: https://test.pypi.org/simple/
Collecting deepreg
  Downloading https://test-files.pythonhosted.org/packages/88/7b/cf98a6e6373c83e9ed7afa9d77f8cc8e23657eac60c52986f7eafcdaecd0/deepreg-0.1.5.1-py3-none-any.whl (72 kB)
     |████████████████████████████████| 72 kB 732 kB/s 
Collecting h5py
  Downloading https://test-files.pythonhosted.org/packages/5a/19/d619759240421c9b51114369752207105003d245467dd2c6c0e6273d24be/h5py-2.3.1.tar.gz (1.1 MB)
     |████████████████████████████████| 1.1 MB 618 kB/s 
Collecting sphinx-rtd-theme
  Downloading https://test-files.pythonhosted.org/packages/fa/da/e9baf7233f8b64d32ccf69472d73d1930d49cb9fface53d9e950e80eab9f/sphinx_rtd_theme-0.3.1-py2.py3-none-any.whl (5.4 MB)
     |████████████████████████████████| 5.4 MB 869 kB/s 
**ERROR: Could not find a version that satisfies the requirement nibabel (from deepreg) (from versions: none)
ERROR: No matching distribution found for nibabel (from deepreg)**`

**Comment by zacbaum** [comment]
> @zacbaum errored: ☹️
> tried pip installing in a new conda env (python 3.7)
> `pip install -i https://test.pypi.org/simple/ deepreg ... **ERROR: Could not find a version that satisfies the requirement nibabel (from deepreg) (from versions: none) ERROR: No matching distribution found for nibabel (from deepreg)**`
> 
> and
> 
> `ERROR: No matching distribution found for tqdm (from deepreg)`
> 
> EDIT: Odd behaviour, running `pip install -i https://test.pypi.org/simple/ deepreg` several times resolves this, but keeps running into ERRORs: for distributions. Re-running the command seems to solve this, but obviously not ideal.

Ok - solved this.

The link on testpypi is bad. What happens is that if you use that it will look for packages that are also on testpypi and not the ones that are on pypi. Therefore, it's not finding most of the packages because they don't exist on that site.

Instead, install with: `pip install deepreg --extra-index-url=https://test.pypi.org/simple/`

Will update the PR description.

**Comment by NMontanaBrown** [comment]
- [x] Checked that links are working
- [x] Was able to pip install with the updated command with no issues.
- [ ] Check functionalities..?

@zacbaum

**Comment by zacbaum** [comment]
> * [ ]  Check functionalities..?

I ran all tests (same as done in CI) using the installed package from pip - not sure if this is enough, but I wasn't sure what else was good to test!

**Comment by YipengHu** [comment]
> > * [ ]   Check functionalities..?
> 
> I ran all tests (same as done in CI) using the installed package from pip - not sure if this is enough, but I wasn't sure what else was good to test!

Happy to merge now - if problem deal with it then

**Comment by NMontanaBrown** [comment]
I also

> > > * [ ]    Check functionalities..?
> > 
> > 
> > I ran all tests (same as done in CI) using the installed package from pip - not sure if this is enough, but I wasn't sure what else was good to test!
> 
> Happy to merge now - if problem deal with it then

Also checked and ok!

**Review by NMontanaBrown — APPROVED** [review]

**Pull request merged**
