### PR TITLE
289 readthedocs

### LINKED ISSUE #289: Docs: Generate ReadTheDocs
# Issue description

Generate ReadTheDocs via Sphinx.

## Type of Issue

Please delete options that are not relevant.

- [x] New feature request
- [x] Documentation update

### PR DESCRIPTION
**Pull request by mathpluscode**
# Description

Put on all demo readmes and restructure demo pages.

Fixes #289

## Type of change

- [ ] Doc change

### CODE REVIEW

**Comment by mathpluscode** [comment]
Use https://deepreg.readthedocs.io/en/289-readthedocs/demo/introduction.html to review

**Comment by mathpluscode** [comment]
@YipengHu I think it would be better to provide an example README file for the DeepReg demo, instead of just listing lists on the page. What do you think?

**Comment by YipengHu** [comment]
> @YipengHu I think it would be better to provide an example README file for the DeepReg demo, instead of just listing lists on the page. What do you think?

Sounds good. But can we leave it until the demo are sorted next week?

**Review by YipengHu — APPROVED** [review]
@mathpluscode I thought you are not changing the demos. Are these required for the RTD? Anyway, now we have to merge with #315 ... i will do that after approving this.

**Comment by YipengHu** [comment]
@mathpluscode I am merging this now so i can combine #315 before it's PR

**Pull request merged**
