### PR TITLE
221 ct lung demos update

### LINKED ISSUE #217: Change from DeepReg version to commit id in README of ct_lung demos
# Issue description

## Type of Issue

- [x] Documentation update

#### What's the expected result?

README contains commit id instead of DeepReg version

### LINKED ISSUE #221: Update both ct_lung demos to be compatible with current version of DeepReg
# Issue description

Some scripts in the demos need some minor modifications to function with the current version of deepreg. 

## Type of Issue

- [x] New feature request

#### What's the expected result?

Both demos work with new changes out of the box

### PR DESCRIPTION
**Pull request by s-sd**
# Description

Made some minor changes to ct lung demos which allows them to work with current deepreg version
Fixes #221 
Fixes #217 

## Type of change

Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

ran demos locally

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by mathpluscode** [comment]
@s-sd do you need review here, is yest plz ask someone. ideally i would argue that the reviewer should run this thing by himself/herself, but im not sure i can do this during this weekend lol

**Comment by YipengHu** [comment]
> @s-sd do you need review here, is yest plz ask someone. ideally i would argue that the reviewer should run this thing by himself/herself, but im not sure i can do this during this weekend lol

@mathpluscode  good point. Let me know when this is ready, otherwise request the reviewer you think is best.

**Comment by s-sd** [comment]
@YipengHu, it is ready, would be great if you could review it but if not, I can assign someone else

**Comment by s-sd** [comment]
@YipengHu, thanks alot for taking a look. I have just tried to run the demo_data script and it finished without an error for me on the candi server. From what I can gather, I think the script does not handle being run more than once which is why I think maybe it somehow ran when the files were already renamed, which caused the NameError. From what I had in the past, the unique lists error also appears for me only when the demo_data script has been run multiple times. Would it be possible to run the script in a fresh clone of the branch (without any of the data for this demo being present prior to running the demo_data script)? Might be that some data was duplicated in the download or the script was run more than once

I will also try to change to the tensorflow function for the download once this error is resolved

**Comment by YipengHu** [comment]
> @YipengHu, thanks alot for taking a look. I have just tried to run the demo_data script and it finished without an error for me on the candi server. From what I can gather, I think the script does not handle being run more than once which is why I think maybe it somehow ran when the files were already renamed, which caused the NameError. From what I had in the past, the unique lists error also appears for me only when the demo_data script has been run multiple times. Would it be possible to run the script in a fresh clone of the branch (without any of the data for this demo being present prior to running the demo_data script)? Might be that some data was duplicated in the download or the script was run more than once
> 
> I will also try to change to the tensorflow function for the download once this error is resolved

I see - will do it now.

**Comment by s-sd** [comment]
@YipengHu, also could you run it from the main DeepReg directory by doing:
```
python3 demos/paired_ct_lung/demo_data.py
``` 
I tested using this so might be that it was run from a different place compared to when I ran it

**Comment by YipengHu** [comment]
@s-sd they tun ok - do you want me to approve it now or wait for any other things you would like to bundle in this PR?

**Comment by s-sd** [comment]
@YipengHu, thanks alot! I am only planning to change the download to the tensorflow function instead of wget. Will merge after that

**Comment by s-sd** [comment]
@YipengHu, changed to the function `tf.keras.utils.get_file` for the download. Would be great if you could review/ approve again.

**Pull request merged**
