### PR TITLE
Issue #167: Add value range requirements for images and labels.

### LINKED ISSUE #167: Docs: Explaination for labels
# Issue description

From @acasamitjana:

- Loading labels: they should be between [0,1]. Do you support multiclass? In that case, should I normalize them between [0,1] or yo expect one-hot encoding? I'm not sure because most of the losses expect binary labels (e.g: cross_entropy o generalized dice) but in the "validate_images_and_labels" you allow 4-D volumes (I guess with one-hot encoding).

- Just a quick comment: I'm not sure it is specified that images/volumes should be between [0,255]. You prevent in "validate_images_and_labels" that volumes are between [0,255] but not that images are originally between [0,1] (which will then be [0,1/255])

Responses:
- for the multi class, assuming an image of shape [d1, d2, d3] have two segmentations, we suppose the labels should be like [d1, d2, d3, 2] so that each channel correspond to one class and each channel is binary, but more docs should be added for this point

- the assumption is, if it's image data, when loading, from nifti or h5, the value range will be 0-255 int, and therefore we will divide them by 255, for label data, the range should be 0 or 1, then we dont change it, so the objective is to make sure all inputs have values between 0-1, i should probably update the error message to make it clear and update the corresponding page

## Type of Issue

- [ ] Documentation update

### PR DESCRIPTION
**Pull request by mathpluscode**
# Description

Update docs to explain the images are assumed to have value between 0 and 255, and labels are assumed to be binary.

The changes are only readme and error messages, so CI is skipped.

Fixes #167

## Type of change

- [x] This change is a documentation update

### CODE REVIEW

**Comment by acasamitjana** [comment]
Hey, thanks @mathpluscode. 
My comments:

- I agree on the use of "multiple labels", also because it'll be consistent throughout the documentation.

- With regards to the raised error, I'm more inclined to include "refer to docs/doc_data_loader.md for more detailed information" rather than a more detailed explanation here.

- In the label part of the doc_data_loader.md file I'd relate it to "one-hot encoding" as many people is familiar with this. Something like: "In case of multiple labels, please use one-hot encoding to transform them into multiple channels such that each class has its own binary label."

**Comment by YipengHu** [comment]
> Hey, thanks @mathpluscode.
> My comments:
> 
> * I agree on the use of "multiple labels", also because it'll be consistent throughout the documentation.
> * With regards to the raised error, I'm more inclined to include "refer to docs/doc_data_loader.md for more detailed information" rather than a more detailed explanation here.
> * In the label part of the doc_data_loader.md file I'd relate it to "one-hot encoding" as many people is familiar with this. Something like: "In case of multiple labels, please use one-hot encoding to transform them into multiple channels such that each class has its own binary label."

Agree on all three points (not often from me :p )!

**Comment by mathpluscode** [comment]
@YipengHu @acasamitjana Sorry for the delay, i updated the docs, please recheck!

**Comment by mathpluscode** [comment]
@acasamitjana @YipengHu hold on, plz DO NOT merge this, the test failed randomly. https://travis-ci.org/github/DeepRegNet/DeepReg/jobs/709607070

**Pull request merged**
