### PR TITLE
using https instead for git clone

### LINKED ISSUE #523: Git clone url
Git clone instructions in documentation to be updated to include url type link

### PR DESCRIPTION
**Pull request by YipengHu**
# Description

Change the ssh protocol to https for better applicability for wider users, in git clone

Fixes #523 

## Type of change

- [x] Documentation Update (fix or improvement on the documentation)

### CODE REVIEW

**Comment by YipengHu** [comment]
@mathpluscode @NMontanaBrown small change- please approve.

**Comment by NMontanaBrown** [comment]
> @mathpluscode @NMontanaBrown small change- please approve.

Can you rename your commit to ascribe to # issue <number> so it's not floating?

**Review by NMontanaBrown — APPROVED** [review]
I tested this on my terminal and it works fine, happy to approve 😄

**Comment by mathpluscode** [comment]
@YipengHu I argue to provide both options? https or git, as using cmd with https it's required to enter passwords.

**Comment by YipengHu** [comment]
> @YipengHu I argue to provide both options? https or git, as using cmd with https it's required to enter passwords.

No it does not require password unless a private project.

**Review by mathpluscode — APPROVED** [review]

**Pull request merged**
