### PR TITLE
584 demo grouped cardiac

### LINKED ISSUE #584: Demo optimise - grouped cardiac
## Subject of the issue

data will remain
hyperparameter tuning and
longer training

### PR DESCRIPTION
**Pull request by YipengHu**
# Description

Demo config updated with new pretrained model uploaded to the zoo.
- bigger model with 32 initi_ch downloading multi-part big pretrained model
- change to mutual information
- training longer than 3/4000 does not seem improving further
- larger regularisation weight made the change difficult to spot but may still be considered plausible 

Fixes #584 

## Type of change

What types of changes does your code introduce to DeepReg?

_Please check the boxes that apply after submitting the pull request._

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation Update (fix or improvement on the documentation)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Other (if none of the other choices apply)

## Checklist

_Please check the boxes that apply after submitting the pull request._

_If you're unsure about any of them, don't hesitate to ask. We're here to help! This is
simply a reminder of what we are going to look for before merging your code._

- [x] I have
      [installed pre-commit](https://deepreg.readthedocs.io/en/latest/contributing/setup.html)
      using `pre-commit install` and formatted all changed files. If you are not
      certain, run `pre-commit run --all-files`.
- [x] My commits' message styles matches
      [our requested structure](https://deepreg.readthedocs.io/en/latest/contributing/commit.html),
      e.g. `Issue #<issue number>: detailed message`.
- [x] I have updated the
      [change log file](https://github.com/DeepRegNet/DeepReg/blob/main/CHANGELOG.md)
      regarding my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by YipengHu** [comment]
Another demo updated, @mathpluscode @s-sd can you have a look please? Attached are two example cases show some local areas been "improved" by the registration.
Overall, this demo has images are looking for very local/fine alignment, whose efficacy would be sensitive to the parameters. I chose a set that showed some visible changes for demonstration purpose.

**Comment by mathpluscode** [comment]
@YipengHu the changed files are not only limited to grouped demos?

**Comment by YipengHu** [comment]
@mathpluscode @s-sd you can look at this PR now.

**Comment by mathpluscode** [comment]
Sync with main first?

**Comment by YipengHu** [comment]
> Sync with main first?

done - the update on the main was already in this PR - github is not as clever as i thought...

**Review by mathpluscode — APPROVED** [review]

**Review by s-sd — APPROVED** [review]

**Pull request merged**
