### PR TITLE
575 demo paired lung

### LINKED ISSUE #575: Demo optimise - paired lung ct
## Subject of the issue
Reduce the input data size
loss weights, init. no. channels
train longer

### PR DESCRIPTION
**Pull request by YipengHu**
# Description

Updated demo with a new pretrained model.
- bigger model and longer training;
- smaller data size during preprocessing for demo purpose;
- stronger regularisation to avoid too large local deformation
- stronger image similarity to align foreground structures without labels such as airways/vessels
- limitation: this is a typical example that the moving image has a much smaller FOV than than of the fixed image (although arguably it may not be necessary for many clinical applications). A general strategy to deal with this probably is yet available, but tools could include overlap-invariant similarity measures, masking, inverse-consistency constraint... (another ticket) 

Fixes #575 

## Type of change

What types of changes does your code introduce to DeepReg?

_Please check the boxes that apply after submitting the pull request._

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation Update (fix or improvement on the documentation)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Other (if none of the other choices apply)

## Checklist

_Please check the boxes that apply after submitting the pull request._

_If you're unsure about any of them, don't hesitate to ask. We're here to help! This is
simply a reminder of what we are going to look for before merging your code._

- [x] I have
      [installed pre-commit](https://deepreg.readthedocs.io/en/latest/contributing/setup.html)
      using `pre-commit install` and formatted all changed files. If you are not
      certain, run `pre-commit run --all-files`.
- [x] My commits' message styles matches
      [our requested structure](https://deepreg.readthedocs.io/en/latest/contributing/commit.html),
      e.g. `Issue #<issue number>: detailed message`.
- [x] I have updated the
      [change log file](https://github.com/DeepRegNet/DeepReg/blob/main/CHANGELOG.md)
      regarding my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by YipengHu** [comment]
This is an interesting demo whose pretrained model has been updated @s-sd @NMontanaBrown @mathpluscode you might be interested in reviewing?
- adding regularisation and image similarity for better foreground alignment
- didn't try the hessian filtering (arguably out of the scope of deepreg)

**Review by s-sd — COMMENTED** [review]
Looks great @YipengHu! As I understand, the changes from branch `584-demo-grouped-cardiac` have already been merged into this branch so the changes in PR #593 are already covered in this PR, which means that we only need to merge this one to `main`. So it might be a good idea to update the description of this PR to state that both issues #584 and #575 have been fixed in this PR and then the description and title can be updated as well. Also files for the `unpaired_us_prostate_cv` demo have been modified so maybe we could add that to the description of the PR as well.

**Comment by YipengHu** [comment]
> Looks great @YipengHu! As I understand, the changes from branch `584-demo-grouped-cardiac` have already been merged into this branch so the changes in PR #593 are already covered in this PR, which means that we only need to merge this one to `main`. So it might be a good idea to update the description of this PR to state that both issues #584 and #575 have been fixed in this PR and then the description and title can be updated as well. Also files for the `unpaired_us_prostate_cv` demo have been modified so maybe we could add that to the description of the PR as well.

Interesting point. I "pre-merged" the previous two because all modified the changelog so I did 't need to "pretentiously" change them independently and merge again... And if the three tickets were dealt with chronically, you would not see these merged changes from other tickets... Ok I'll let you know when the previous one is merged.

**Comment by YipengHu** [comment]
ok - the last one (for now ;) @s-sd @mathpluscode

**Review by s-sd — APPROVED** [review]

**Review by mathpluscode — APPROVED** [review]

**Pull request merged**
