### PR TITLE
Issue #546: do not use mirror strategy unless there are >= 2 GPUs

### LINKED ISSUE #546: Do not use mirror strategy unless there are >= 2 GPUs
## Subject of the issue

Now we are using mirror strategy regardless of the device we are using.
So it's better to improve this.

The example code from tf guide https://www.tensorflow.org/guide/distributed_training#using_tfdistributestrategy_with_tfkerasmodelfit is
 
```python
if tf.config.list_physical_devices('gpu'):
  strategy = tf.distribute.MirroredStrategy()
else:  # use default strategy
  strategy = tf.distribute.get_strategy() 

with strategy.scope():
  # do something interesting
  print(tf.Variable(1.))
```

The code above is not enough as we need to check how many GPUs we have. `tf.config.list_physical_devices('gpu')` is returning a list, so it's super easy to fix it.

## Expected behaviour

Do not use mirror strategy when <= 1 GPU.

## Actual behaviour

Mirror strategy is used even without GPU.

### PR DESCRIPTION
**Pull request by kate-sann5100**
# Description

Only use mirror strategy when there are more than 1 GPUs.

Fixes #546

## Type of change

What types of changes does your code introduce to DeepReg? _Put an `x` in the boxes that
apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation Update (fix or improvement on the documentation)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR.
If you're unsure about any of them, don't hesitate to ask. We're here to help! This is
simply a reminder of what we are going to look for before merging your code._

- [x] I have
      [installed pre-commit](https://deepreg.readthedocs.io/en/latest/contributing/setup.html)
      using `pre-commit install` and formatted all changed files. If you are not
      certain, run `pre-commit run --all-files`.
- [x] My commits' message styles matches
      [our requested structure](https://deepreg.readthedocs.io/en/latest/contributing/commit.html),
      e.g. `Issue #<issue number>: detailed message`.
- [x] I have updated the
      [change log file](https://github.com/DeepRegNet/DeepReg/blob/main/CHANGELOG.md)
      regarding my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by mathpluscode** [comment]
Hi @NMontanaBrown, this is my friend in Oxford @kate-sann5100 Yiwen, Li, who is joining us to contribute to DeepReg!

This is her first PR! But the `Codedev` was not happy as the >1 GPU case was not tested :( well ofc not as in CI we do not have GPUs at all. Maybe we will have to force the merge? any other solutions?

image

**Comment by mathpluscode** [comment]
> Hi @NMontanaBrown, this is my friend in Oxford @kate-sann5100 Yiwen, Li, who is joining us to contribute to DeepReg!
> 
> This is her first PR! But the `Codedev` was not happy as the >1 GPU case was not tested :( well ofc not as in CI we do not have GPUs at all. Maybe we will have to force the merge? any other solutions?
> 
> image

oh actually got it solved :) by adding a comment to ignore that line.

**Review by mathpluscode — APPROVED** [review]

**Comment by NMontanaBrown** [comment]
Hi, I will review this PR today, after testing locally on a machine with more than one GPU! Thanks for contributing @kate-sann5100 😄

**Comment by mathpluscode** [comment]
> Hi, I will review this PR today, after testing locally on a machine with more than one GPU! Thanks for contributing @kate-sann5100

any updates :) btw the multi GPU behaviours are not changed by this MR

**Comment by NMontanaBrown** [comment]
Hi, apologies for delay, reviewing now! @mathpluscode @kate-sann5100

**Review by NMontanaBrown — CHANGES_REQUESTED** [review]
Merge conflicts with CHANGELOG from new updates may need to be resolved, otherwise ok!

**Review by NMontanaBrown — APPROVED** [review]

**Pull request merged**
