### PR TITLE
344 automate test on demos

### LINKED ISSUE #344: Automate test on demos
# Issue description

As we are having multiple demos and they are not covered by tests, it would be important for our release/deployment later to make sure that the new version of DeepReg still supports all demos. So that demo no longer needs to specify the last checked commit.

For each demo, we need to at least perform the following steps automatically.
- download and preprocess data
- launch training for 1 epoch
- perform prediction

# TODO

Here are some more to optimize in a later stage
- for demo `paired_ct_lung` and `paired_mrus_brain`
  - Downloaded files for pretrained model contains multiple ckpts, we can simplify to only the last one.
  - Need to refactor data preprocessing script.
  - Question: why using `main_path = os.getcwd()` to change current dir?
- `paired_mrus_brain` the full data download URL not longer works
- `paired_ct_lung` and `unpaired_ct_lung` have some commented code related to ge
- `paired_ct_lung`, `paired_mrus_brain` and `unpaired_ct_lung` demos have many duplicated code.
- Add a CLI tool to automate the process of adding a demo.

### PR DESCRIPTION
**Pull request by mathpluscode**
# Description

Uniform demo scrips and cover them by test

Fixes #344

Check https://deepreg.readthedocs.io/en/344-automate-test-on-demos/demo/introduction.html for preview.

## Type of change

What types of changes does your code introduce to DeepReg? _Put an `x` in the boxes that
apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [x] Documentation Update (fix or improvement on the documentation)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Other (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR.
If you're unsure about any of them, don't hesitate to ask. We're here to help! This is
simply a reminder of what we are going to look for before merging your code._

- [x] I have
      [installed pre-commit](https://deepreg.readthedocs.io/en/latest/contributing/setup.html)
      using `pre-commit install` and formatted all changed files. If you are not
      certain, run `pre-commit run --all-files`.
- [x] My commits' message styles matches
      [our requested structure](https://deepreg.readthedocs.io/en/latest/contributing/commit.html),
      e.g. `Issue #<issue number>: detailed message`.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### classical_ct_headneck_affine

- [x] Readme page checked in RTD.
- [x] Executed all scripts (data, train, predict, register) and no error.

#### classical_mr_prostate_nonrigid

- [x] Readme page checked in RTD.
- [x] Executed all scripts (data, train, predict, register) and no error.

#### grouped_mask_prostate_longitudinal

- [x] Readme page checked in RTD.
- [x] Executed all scripts (data, train, predict, register) and no error.

#### grouped_mr_heart

- [x] Readme page checked in RTD.
- [x] Executed all scripts (data, train, predict, register) and no error.

#### paired_ct_lung

- [x] Readme page checked in RTD.
- [x] Executed all scripts (data, train, predict, register) and no error.

#### paired_mrus_brain

- [x] Readme page checked in RTD.
- [x] Executed all scripts (data, train, predict, register) and no error.

#### paired_mrus_prostate

- [x] Readme page checked in RTD.
- [x] Executed all scripts (data, train, predict, register) and no error.

#### unpaired_ct_abdomen

- [x] Readme page checked in RTD.
- [x] Executed all scripts (data, train, predict, register) and no error.

#### unpaired_ct_lung

- [x] Readme page checked in RTD.
- [x] Executed all scripts (data, train, predict, register) and no error.

#### unpaired_mr_brain

- [x] Readme page checked in RTD.
- [x] Executed all scripts (data, train, predict, register) and no error.

#### unpaired_us_prostate_cv

- [x] Readme page checked in RTD.
- [x] Executed all scripts (data, train, predict, register) and no error.

### CODE REVIEW

**Comment by mathpluscode** [comment]
Hi @YipengHu @ebonmati @s-sd @acasamitjana, as you may know, I've been talking about the automated test for all demos for a while. As JOSS reviewer had some problems with the demo, ref #478, it became more urgent.

As a result, I've uniformed all the demos as follows:
1. All data are stored under `dataset/train`, `dataset/valid`, `dataset/test`. Before some demo used `data` folder
2. Pretrained model checkpoints are saved under `dataset/pretrained`. Before some are stored outside `dataset`.
3. All demo shared the similar `demo_train` and `demo_predict` which allows a test mode training. 
4. I've uniformed the readme files (while preserving as many custom details as I can like used pre-processing methods, different training methods etc.)

Therefore, I invite you to check the demos you've written before and tell me if there's anything you don't like etc.
We may discuss how we share the workload to test all demos manually again. (I've tested it with pytest already, but just in case ^^)

**Comment by YipengHu** [comment]
running fine - can i suggest simplify the demo scripts? the demo is more useful for those that are not familier with coding or just want to use config - if all are programmed, the use of the equivalent CLI is not abvious. I personally do not agree that changing the predict/train scripts to a module is a good idea. They should remain just scripts, without functions/classes.

**Comment by s-sd** [comment]
Hi @mathpluscode ! 

I've checked the `paired_ct_lung`, `unpaired_ct_lung` and `paired_mrus_brain` demos and they work fine. 

Regarding the visualisations, it is okay to remove them from the predict script. For Issue #474, I am planning to add a small visualisation section to the readme of the demos which will have a command for the deepreg_vis tool to create a gif from the predict output. I will do this after this PR is merged.

For #478, I believe this error only occurs if the script is stopped in the middle on the first run (for example by a keyboard interrupt) and then is re-run later. A simple solution is to remove the partially processed files and run again. So I suggest that we add an informative error message that tells the user to remove the files and re-run and also a small message like 'This can take a few minutes' where the script takes a little while so the user is less inclined to stop the script. If this is okay, can I add this in this PR or would it be better to open a new ticket or make a commit/ PR under #478?

Regarding simplifying the demo scripts, I also think that having it just as a script would make it easier to read which would in turn make it easier for the user to modify the script as they like or to work out an equivalent CLI command.

**Comment by mathpluscode** [comment]
I can't test those scripts under demo mode without argparse.
Otherwise it gonna run with default config which takes hours.

If you have any ideas for improving this?
@YipengHu @s-sd

**Comment by mathpluscode** [comment]
> running fine - can i suggest simplify the demo scripts? the demo is more useful for those that are not familier with coding or just want to use config - if all are programmed, the use of the equivalent CLI is not abvious. I personally do not agree that changing the predict/train scripts to a module is a good idea. They should remain just scripts, without functions/classes.

I personally against one straight script. Even in many notebook tutorials we define functions. Specially it's just one or two functions which should be super easy to understand. Also argparse is super easy and popular.

For user feedbacks, we may wait until user raise issues I'd say.

**Comment by mathpluscode** [comment]
> Hi @mathpluscode ! 
> 
> 
> 
> I've checked the `paired_ct_lung`, `unpaired_ct_lung` and `paired_mrus_brain` demos and they work fine. 
> 
> 
> 
> Regarding the visualisations, it is okay to remove them from the predict script. For Issue #474, I am planning to add a small visualisation section to the readme of the demos which will have a command for the deepreg_vis tool to create a gif from the predict output. I will do this after this PR is merged.
> 
> 
> 
> For #478, I believe this error only occurs if the script is stopped in the middle on the first run (for example by a keyboard interrupt) and then is re-run later. A simple solution is to remove the partially processed files and run again. So I suggest that we add an informative error message that tells the user to remove the files and re-run and also a small message like 'This can take a few minutes' where the script takes a little while so the user is less inclined to stop the script. If this is okay, can I add this in this PR or would it be better to open a new ticket or make a commit/ PR under #478?
> 
> 
> 
> Regarding simplifying the demo scripts, I also think that having it just as a script would make it easier to read which would in turn make it easier for the user to modify the script as they like or to work out an equivalent CLI command.

For issues related to the partial files, are they only linked to data or also for train predict?

For testing I removed the dataset folder and all zips beforehand.

We can do the same for each demo, like
- if you run demo_data it will clean files beforehand
- for train and predict, I didn't add tine stamp to the output file but maybe it's better to add it back.

So I think we can solve this issue inside this PR :)

**Comment by s-sd** [comment]
@mathpluscode 

> For user feedbacks, we may wait until user raise issues I'd say.

yeah I think that sounds good

> For issues related to the partial files, are they only linked to data or also for train predict?
>
> For testing I removed the dataset folder and all zips beforehand.
>
> We can do the same for each demo, like
>
> if you run demo_data it will clean files beforehand
> for train and predict, I didn't add tine stamp to the output file but maybe it's better to add it back.
> So I think we can solve this issue inside this PR :)

for the partially processed files, they are processed in the demo_data script and then subsequently used in the train and predict script so if the data has not been properly processed, it will cause the train and predict scripts to also give errors. If you mean the outputs created by train and predict, then they are overwritten if the train or predict script is run multiple times so in that sense, this is not a problem for train and predict.

I think what you are suggesting will help avoid problems in demo_data which then progress onto train and predict. If any existing files are removed before running the demo_data script then the problem will be solved and the user can stop the script in the middle and then re-run without problems.

**Comment by mathpluscode** [comment]
@s-sd sure. Then I will add the removal.

**Comment by YipengHu** [comment]
> I can't test those scripts under demo mode without argparse.
> Otherwise it gonna run with default config which takes hours.
> 
> If you have any ideas for improving this?
> @YipengHu @s-sd

No much we can do here, we need draw a line between "being realistic" and "being demo-friendly"

**Comment by YipengHu** [comment]
> > running fine - can i suggest simplify the demo scripts? the demo is more useful for those that are not familier with coding or just want to use config - if all are programmed, the use of the equivalent CLI is not abvious. I personally do not agree that changing the predict/train scripts to a module is a good idea. They should remain just scripts, without functions/classes.
> 
> I personally against one straight script. Even in many notebook tutorials we define functions. Specially it's just one or two functions which should be super easy to understand. Also argparse is super easy and popular.
> 
> For user feedbacks, we may wait until user raise issues I'd say.

Sorry i have not been very specific. I think you were probably right, I'd be happy with just removing the main functions. For tutorial purposes, i argue this is the "standard practice" to use more "scripty" scripts:
https://keras.io/examples/vision/image_classification_from_scratch/
https://www.tensorflow.org/tutorials/keras/classification
https://www.tensorflow.org/tutorials/quickstart/advanced

**Comment by mathpluscode** [comment]
@YipengHu @s-sd I've done the following

- remove data folders before preparing data inside data_demo
- flatten train/predict scripts, so no more `main`
- add timestamp to log dirs, so run `train` or `predict` multiple times will be saved in different folders

Please try again and click the check box in this issue above for each demo ^^

**Comment by s-sd** [comment]
Thanks @mathpluscode! I've checked three of the demos (ticked in the description above) and they all work well. I also checked by stopping and re-running the `demo_data` script and the problem with the partially processed files is also fixed now.

**Comment by acasamitjana** [comment]
@mathpluscode , just two quick questions/comments to catch up:
1.- What is the register script? I guess it should perform train+predict in one script. Is it required for all demos?
2.- I see changes in config files for demos and I'm not sure why.

**Comment by mathpluscode** [comment]
> @mathpluscode , just two quick questions/comments to catch up:
> 1.- What is the register script? I guess it should perform train+predict in one script. Is it required for all demos?
> 2.- I see changes in config files for demos and I'm not sure why.

@acasamitjana 

1. the register script is for classical methods, there was only one script before my changes
2. the change in config is because the given config is inconsistent with the config used for the training, you can check the demo by downloading the file manually (running the script will delete the zip automatically), and the code was using the config along with ckpt ;)

**Comment by acasamitjana** [comment]
I have tested all three scripts and commit a minor change in the readme file for the mr_brain demo.

**Comment by YipengHu** [comment]
classical_ct_headneck_affine:
by default, the demo_register stopped after Step 0.
This is a demo not a test, it should allow user to complete the registration and see reasonable results;
In script, i don't think we should add unnecessary code to facilitate testing, such that the demo script becomes more complicated than it needs to be.

**Review by YipengHu — APPROVED** [review]

**Comment by mathpluscode** [comment]
@s-sd @acasamitjana do you have any more comments ;) ?

**Review by s-sd — APPROVED** [review]
@mathpluscode, I don't have any more comments, looks good I think

**Pull request merged**
