### PR TITLE
427 and 447 readme updates

### LINKED ISSUE #427: Adding JOSS Badge to README.md
## Subject of the feature

Now that the review has officially begun (TBC within 6 or so weeks) we can add a badge to the repo which illustrates that submission (and hopefully acceptance) has occurred for those that are interested.

If the feature request is approved, would you be willing to submit a PR? _(Help can be
provided if you need assistance submitting a PR)_

Yes

E.g.

[status](https://joss.theoj.org/papers/7e6de472bc82a70d7618e23f618960b3)

### LINKED ISSUE #447: Add MEC badge for notebook
## Subject of the documentation

As we won the first price, time to add this info to README.

But for now, the website https://miccai-sb.github.io/materials.html hasn't been updated yet.

@YipengHu mentioned that there's a badge for it as well.

### PR DESCRIPTION
**Pull request by zacbaum**
# Description

Modified README to add JOSS badges and MEC information.

Fixes #427 
Fixes #447 

## Type of change

What types of changes does your code introduce to DeepReg? _Put an `x` in the boxes that
apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Documentation Update (fix or improvement on the documentation)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR.
If you're unsure about any of them, don't hesitate to ask. We're here to help! This is
simply a reminder of what we are going to look for before merging your code._

- [x] I have
      [installed pre-commit](https://deepreg.readthedocs.io/en/latest/contributing/setup.html)
      using `pre-commit install` and formatted all changed files. If you are not
      certain, run `pre-commit run --all-files`.
- [x] My commits' message styles matches
      [our requested structure](https://deepreg.readthedocs.io/en/latest/contributing/commit.html),
      e.g. `Issue #<issue number>: detailed message`.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by zacbaum** [comment]
@mathpluscode @YipengHu @NMontanaBrown, please assign yourself as a reviewer if you have a chance to check up on these changes - and let me know of any suggestions.

@YipengHu sorry to take over #447 without asking; figured easier to get it all done in one PR 👍🏼

**Review by YipengHu — APPROVED** [review]
Thanks Zac! Sorry being slow on #447 - was waiting for some official announcement web page becomes alive ;) which never happened.... so good idea to get this in now.

**Comment by zacbaum** [comment]
My pre-commit is obviously still not working properly for `.md` - if someone can check this out locally and commit a reformatted version that would be appreciated.

@YipengHu @mathpluscode @NMontanaBrown

**Comment by mathpluscode** [comment]
> My pre-commit is obviously still not working properly for `.md` - if someone can check this out locally and commit a reformatted version that would be appreciated.
> 
> 
> 
> @YipengHu @mathpluscode @NMontanaBrown 

@zacbaum could you open a new issue regarding the problem of pre-commit and conda installation? The whole error log will be really helpful for debugging. Thx!

**Review by mathpluscode — APPROVED** [review]

**Pull request merged**
